In [12]:
import joblib
import pandas as pd

In [13]:
test_data_path = "test_x.csv"
test_data = pd.read_csv(test_data_path)
test_data

,Unnamed: 0,Hour,Minutes,Sensor_alpha,Sensor_beta,Sensor_gamma,Sensor_alpha_plus,Sensor_beta_plus,Sensor_gamma_plus
0,7000,21,31,-72.083585,-11.434977,-52.961743,-72.696385,145.299227,-143.856243
1,7001,21,3,-193.619980,40.137081,85.419244,-26.266801,-125.391237,80.904973
2,7002,22,31,42.578382,-51.613402,125.055611,182.136746,-9.726951,-114.913402
3,7003,21,25,-64.150951,287.306752,-70.965473,13.789738,38.187260,137.761691
4,7004,18,11,193.750787,-61.989533,-110.347066,-16.864786,148.541916,232.424616
...,...,...,...,...,...,...,...,...,...
2995,9995,3,26,-101.913083,87.337077,77.193476,-79.694034,13.273965,143.004786
2996,9996,21,6,52.424913,-37.107249,120.373905,208.090551,-135.567057,-53.867634
2997,9997,21,0,-103.295133,34.736979,-195.018118,-164.294768,-26.993064,6.063715
2998,9998,20,13,170.027159,-73.100306,-117.330651,11.353824,-3.366007,-140.113661
2999,9999,19,17,-173.839238,66.386097,-141.968498,197.558808,-44.847981,142.537872

Load the classifier and make the predictions

In [15]:
classifier = joblib.load("classifier.joblib")

In [16]:
y = classifier.predict(test_data)

save predictions to file

In [17]:
submission_data = pd.DataFrame(y)
submission_data.to_csv("results.csv", index=True)